[package]
name = "quantum"
version = "0.1.0"
authors = ["CyanFroste <cyan14froste@gmail.com>"]
edition = "2018"
repository = "https://github.com/CyanFroste/quantum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
